import {courses,courseById,GOAL} from './data/courses.js';
import {createStore,STORAGE_KEY} from './state.js';
import {registerJourneyReader} from './webmcp.js';
// Keep focus management accessible while showing rings only for keyboard input.
document.documentElement.dataset.inputMode='pointer';
window.addEventListener('pointerdown',()=>{document.documentElement.dataset.inputMode='pointer'},{capture:true,passive:true});
window.addEventListener('keydown',event=>{if(!event.metaKey&&!event.ctrlKey&&!event.altKey&&['Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter',' '].includes(event.key))document.documentElement.dataset.inputMode='keyboard'},{capture:true});
const app=document.getElementById('app'),dialog=document.getElementById('modal'),toastEl=document.getElementById('toast');
const $=(s,p=app)=>p.querySelector(s);const n=x=>Math.round(x).toLocaleString('ko-KR');
const iconPaths={arrow:'<path d="M7 17 17 7M7 7h10v10"/>',right:'<path d="M4 12h16m-6-6 6 6-6 6"/>',back:'<path d="M20 12H4m6-6-6 6 6 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',map:'<path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Zm6-3v15m6-12v15"/>',book:'<path d="M3 3h6a4 4 0 0 1 3 2 4 4 0 0 1 3-2h6v17h-6a4 4 0 0 0-3 2 4 4 0 0 0-3-2H3V3Zm9 2v17"/>',route:'<circle cx="6" cy="6" r="3"/><circle cx="18" cy="18" r="3"/><path d="M9 6h7a4 4 0 0 1 0 8H8a4 4 0 0 0 0 8"/>',settings:'<path d="M4 7h16M4 17h16M8 4v6m8 4v6"/>',locate:'<circle cx="12" cy="12" r="7"/><circle cx="12" cy="12" r="2"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3"/>',fit:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 4v3"/>',post:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',home:'<path d="m3 10 9-7 9 7v11h-6v-7H9v7H3V10Z"/>'};
const icon=(name)=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${iconPaths[name]||iconPaths.map}</svg>`;
let toastTimer;let storageProblem='';let storage;try{storage=window.localStorage}catch{storageProblem='브라우저 저장 공간을 사용할 수 없어 현재 화면에서만 기록됩니다.'}
const store=createStore(storage,msg=>{storageProblem=msg;toast(msg)});
const state=()=>store.get(),active=()=>courseById[state().activeCourseId]||courseById.jeju;
let screen='home',zoom=true,selected=Math.min(4,Math.floor((state().courseProgress[state().activeCourseId]?.accumulatedSteps??0)/10000)),moving=false,motionId=0,completion=null,journalTab=state().activeCourseId||'jeju',arrival=null,modalType='',modalOnClose=null,restoreFocus=null;
function toast(message){toastEl.textContent=message;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),3400)}
function action(type,extra={}){try{return store.dispatch({type,...extra})}catch(e){toast(e.message);return false}}
function brand(){return '<button class="brand" data-action="home" aria-label="시작 화면으로">Purrs Lab 트래커<i>.</i></button>'}
function debugButton(){return `<button class="debug-toggle" data-action="debug" aria-label="테스트 걸음 입력 및 데이터 초기화">${icon('settings')} 테스트</button>`}
function nav(){return `<nav class="bottom-nav" aria-label="주요 화면"><button data-action="journey" ${screen==='journey'?'aria-current="page"':''}>${icon('route')}여정</button><button data-action="courses" ${screen==='courses'?'aria-current="page"':''}>${icon('map')}코스</button><button data-action="journal">${icon('book')}엽서 도감</button></nav>`}
function startPage(){const s=state(),progress=s.courseProgress[s.activeCourseId]?.startedAt;return `<header class="topbar"><div class="brand">Purrs Lab 트래커<i>.</i></div><span class="kicker">MONTY</span></header><div class="hero"><span class="hero-tag">MONTY & FRIENDS</span><div class="avatar" role="img" aria-label="배낭을 멘 몬티"></div></div><section class="welcome"><div class="kicker">YOUR EVERYDAY ADVENTURE</div><h1>평범한 하루를,<br>특별한 여정으로.</h1><p>오늘 걸은 만큼, 새로운 풍경을 만나세요.<br>몬티가 당신의 여행을 함께할게요.</p>${progress?`<button class="primary" data-action="journey">이어서 걷기 ${icon('right')}</button><button class="secondary" data-action="courses">다른 여행 고르기</button>`:`<button class="primary" data-action="courses">여행 고르기 ${icon('right')}</button>`}<p class="footnote">${s.lifetimeSteps?`지금까지 함께 걸은 ${n(s.lifetimeSteps)}보`:'한 걸음씩 쌓이는 나만의 여행 이야기'}</p><div class="saved-note">기록은 이 기기의 브라우저에 저장돼요.</div></section>`}
function coursesPage(){return `<header class="topbar"><button class="back" data-action="home" aria-label="시작 화면으로">${icon('back')}</button><strong>여행 고르기</strong>${debugButton()}</header><div class="section-heading"><div class="kicker">CHOOSE YOUR NEXT CHAPTER</div><h1>어떤 풍경을 걸을까요?</h1><p>다섯 번의 발견, 한 번의 특별한 여정.</p></div>${currentCoursePanel()}<section class="course-list" aria-label="여행 코스">${courses.map(c=>c.enabled?`<button class="course-card" data-course="${c.id}"><div class="course-cover" style="--cover:url('${c.map}');--cover-position:${c.coverPosition}"><span class="course-tag">${c.category} · ${c.id.toUpperCase()}</span>${state().activeCourseId===c.id&&state().courseProgress[c.id].startedAt?'<span class="course-active">여행 중</span>':''}</div><div class="course-info"><div><h2>${c.name}</h2><p>${c.description}</p><div class="course-meta"><span>50,000보</span><span>엽서 5장</span></div></div>${icon('arrow')}</div></button>`:`<div class="coming-soon"><strong>${c.name}</strong><small>COMING SOON</small></div>`).join('')}</section>${nav()}`}
function journeyPage(){const s=state(),c=active(),progress=completion?.to??s.courseProgress[c.id].accumulatedSteps;selected=Math.min(selected,4);return `<header class="topbar">${brand()}${debugButton()}</header><section class="journey-header"><p class="course-select-label">함께 걷고 있는 여행</p><h1 class="journey-title">${c.name}</h1><div class="progress-labels"><span><strong id="course-steps">${n(progress)}</strong> / 50,000보</span><span id="course-percent">${Math.round(progress/500)}%</span></div><div class="progress-track" role="progressbar" aria-label="코스 진행률" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${progress/500}"><div class="progress-fill" style="width:${progress/500}%"></div></div><div class="lifetime"><span>${c.category} · ${Object.keys(s.collectedPostcards).filter(k=>k.startsWith(c.id+'_')).length}/5 엽서</span><span>전체 걸음 <b id="lifetime-steps">${n(s.lifetimeSteps)}</b>보</span></div></section><section class="map-shell" aria-label="${c.shortName} 가상 여행 지도"><div class="map-tools"><button data-action="zoom">${icon('fit')}<span>${zoom?'전체 경로':'확대해서 보기'}</span></button><button data-action="locate">${icon('locate')} 내 위치</button></div><div class="map-viewport" role="region" aria-label="여행 지도, 상하좌우로 스크롤해서 탐색"><div class="map-world" style="--map-image:url('${c.map}')"><svg class="map-route" viewBox="0 0 1000 1500" role="img" aria-label="출발점부터 도착지까지 연결된 여행 경로"></svg><div class="map-pins"></div><div class="avatar you-pin" role="img" aria-label="몬티의 현재 위치"></div><div class="start-pin" style="left:${c.start[0]/10}%;top:${c.start[1]/15}%">${c.startName}</div></div></div></section><p class="map-caption">${c.id==='orvel'?'오르벨의 다섯 장소를 잇는 가상 여정':'명소를 담은 가상 여정 · 실제 탐방 경로와 달라요'}</p><section class="waypoint-detail" aria-live="polite"></section><section class="claim-panel"><div class="claim-line"><span class="label">누적된 걸음</span><strong class="value"><span id="pending-steps">${n(s.unclaimedSteps)}</span> <small>보</small></strong></div><button class="primary" data-action="claim" ${s.unclaimedSteps===0?'disabled':''}>이 여정 정산하기 ${icon('right')}</button><p class="claim-help">${s.unclaimedSteps===0?'아직 정산할 걸음이 없어요. <button data-action="debug">테스트 걸음 추가</button>':'날짜가 바뀌어도 정산 전까지 계속 쌓여요.'}</p></section>${nav()}`}
function render(){if(screen==='journey'&&!state().activeCourseId){screen='courses';history.replaceState(null,'','#courses')}const c=active();document.documentElement.style.setProperty('--accent',c.accent);document.documentElement.style.setProperty('--course-bg',c.background);app.className=screen;document.body.classList.toggle('journey-screen',screen==='journey');app.innerHTML=(storageProblem?`<p class="storage-banner" role="status">${storageProblem}</p>`:'')+(screen==='home'?startPage():screen==='courses'?coursesPage():journeyPage());if(screen==='journey'){$('.map-shell').append($('.waypoint-detail'));drawMap();bindDrag()}}
function navigate(target,{locate=true}={}){if(moving)return;if(!['home','courses','journey'].includes(target))target='home';if(target==='journey'&&!state().activeCourseId)target='courses';if(target==='journey')action('start');screen=target;history.replaceState(null,'','#'+target);render();window.scrollTo({top:0,behavior:'instant'});if(target==='journey'&&locate)requestAnimationFrame(()=>centerMap(false))}
function displayedSteps(){return completion?.to??(state().courseProgress[state().activeCourseId]?.accumulatedSteps??0)}
function routePosition(steps){const c=active();if(steps===0)return{x:c.start[0],y:c.start[1]};const p=Math.min(4.99999999,steps/10000),i=Math.floor(p),path=$(`[data-segment="${i}"]`);return path?path.getPointAtLength(path.getTotalLength()*(p-i)):{x:c.start[0],y:c.start[1]}}
function drawMap(){const c=active(),world=$('.map-world');if(!world)return;const viewport=$('.map-viewport'),width=Math.max(660,app.clientWidth*1.55);world.style.width=width+'px';world.style.height=width*1.5+'px';const scale=zoom?1:Math.min(viewport.clientWidth/width,viewport.clientHeight/(width*1.5));world.style.zoom=scale;world.style.margin=zoom?'0':'0 auto';viewport.classList.toggle('is-fit',!zoom);$('.map-route').innerHTML=c.segments.map((d,i)=>`<path data-segment="${i}" d="${d}" fill="none" stroke="#fff9e9" stroke-width="12" stroke-linecap="round"/><path d="${d}" fill="none" stroke="#827f6d" stroke-width="4" stroke-dasharray="5 9" stroke-linecap="round"/><path class="traveled" data-traveled="${i}" d="${d}" fill="none" stroke="${c.accent}" stroke-width="7" pathLength="100" stroke-dasharray="100" stroke-linecap="round"/>`).join('');$('.map-pins').innerHTML=c.waypoints.map((w,i)=>`<button class="waypoint ${displayedSteps()>=w.steps?'is-visited':''} ${selected===i?'is-selected':''} ${i===4?'is-finish':''}" data-waypoint="${i}" style="left:clamp(78px,${w.point[0]/10}%,calc(100% - 78px));top:${w.point[1]/15}%;--pin-color:${w.color}" aria-label="${w.name}, ${n(w.steps)}보"><span class="pin-dot">${displayedSteps()>=w.steps?'✓':i+1}</span><span class="pin-label">${w.name}${i===4?' · 도착':''}</span></button>`).join('');updatePosition(displayedSteps());renderDetail()}
function updatePosition(steps){const p=routePosition(steps);$('.you-pin').style.left=p.x/10+'%';$('.you-pin').style.top=p.y/15+'%';$('#course-steps').textContent=n(steps);$('#course-percent').textContent=Math.round(steps/500)+'%';$('.progress-fill').style.width=steps/500+'%';$('.progress-track').setAttribute('aria-valuenow',steps/500);app.querySelectorAll('[data-traveled]').forEach(el=>{const f=Math.max(0,Math.min(1,steps/10000-Number(el.dataset.traveled)));el.style.strokeDashoffset=100*(1-f)})}
function centerMap(smooth=true,steps=displayedSteps()){const v=$('.map-viewport'),w=$('.map-world');if(!v||!w)return;if(!zoom)return;const p=routePosition(steps);v.scrollTo({left:p.x/1000*w.clientWidth-v.clientWidth*.5,top:p.y/1000*w.clientWidth-v.clientHeight*.37,behavior:smooth&&!reducedMotion()?'smooth':'instant'})}
function renderDetail(){const c=active(),w=c.waypoints[selected],key=`${c.id}_${w.id}`,obtained=!!state().collectedPostcards[key];$('.waypoint-detail').innerHTML=`<div class="waypoint-number">${String(selected+1).padStart(2,'0')}</div><div class="text"><small>${obtained?'수집한 풍경':'앞으로 만날 풍경'} · ${n(w.steps)}보</small><h2>${w.name}</h2><p>${w.subtitle}</p></div>${obtained?`<button class="postcard-open" data-action="selected-postcard" aria-label="${w.name} 엽서 보기">${icon('post')}</button>`:''}`}
function bindDrag(){const v=$('.map-viewport');v.tabIndex=0;let drag=null;v.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.target.closest('button'))return;drag={x:e.clientX,y:e.clientY,left:v.scrollLeft,top:v.scrollTop};v.setPointerCapture(e.pointerId)});v.addEventListener('pointermove',e=>{if(!drag)return;if(Math.abs(e.clientX-drag.x)+Math.abs(e.clientY-drag.y)>4)v.classList.add('dragging');v.scrollLeft=drag.left-e.clientX+drag.x;v.scrollTop=drag.top-e.clientY+drag.y});const end=()=>{drag=null;v.classList.remove('dragging')};v.addEventListener('pointerup',end);v.addEventListener('pointercancel',end);v.addEventListener('keydown',e=>{if(e.target!==v)return;const delta={ArrowDown:[0,80],ArrowUp:[0,-80],ArrowLeft:[-80,0],ArrowRight:[80,0]}[e.key];if(delta){e.preventDefault();v.scrollBy(...delta)}})}
function openDialog(type,content,onClose=null){modalType=type;dialog.dataset.type=type;modalOnClose=onClose;if(!dialog.open)restoreFocus=document.activeElement;dialog.innerHTML=content;dialog.returnValue='';if(!dialog.open)dialog.showModal();dialog.scrollTop=0;const focus=dialog.querySelector('[autofocus]')||dialog.querySelector(type==='journal'?'[aria-selected="true"]':'.close,button');focus?.focus({preventScroll:true})}
function closeDialog(result='cancel'){const callback=modalOnClose;modalOnClose=null;modalType='';dialog.close(result);callback?.(result);if(restoreFocus?.isConnected)restoreFocus.focus({preventScroll:true})}
dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog()});
dialog.addEventListener('keydown',e=>{if(!e.target.dataset.journalTab)return;const i=courses.findIndex(c=>c.id===e.target.dataset.journalTab);const next=e.key==='ArrowRight'?(i+1)%courses.length:e.key==='ArrowLeft'?(i+courses.length-1)%courses.length:e.key==='Home'?0:e.key==='End'?courses.length-1:null;if(next!==null){e.preventDefault();openJournal(courses[next].id)}});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog()}});
function modalHeader(title,sub=''){return `<div class="modal-header"><div><h2 id="modal-title">${title}</h2>${sub?`<p>${sub}</p>`:''}</div><button class="close" data-dialog="close" aria-label="닫기">${icon('close')}</button></div>`}
function confirm(title,body,label='확인',danger=false){return new Promise(resolve=>{openDialog('confirm',modalHeader(title)+`<div class="modal-content"><p class="confirm-copy">${body}</p><div class="modal-actions"><button class="secondary" data-dialog="close" autofocus>취소</button><button class="primary ${danger?'danger':''}" data-dialog="confirm">${label}</button></div></div>`,v=>resolve(v==='confirm'))})}
function currentCoursePanel(){const s=state(),c=courseById[s.activeCourseId];if(!c||!s.courseProgress[c.id].startedAt)return '';return `<section class="current-course"><span class="kicker">지금 함께 걷는 여행</span><h2>${c.name}</h2><p>${n(s.courseProgress[c.id].accumulatedSteps)} / 50,000보</p><div class="current-actions"><button class="primary" data-action="journey">이어서 걷기</button><button class="abandon-button" data-action="abandon">여행 중단하기</button></div></section>`}
async function abandonCourse(){const s=state(),c=courseById[s.activeCourseId];if(!c)return;const yes=await confirm('이 여행을 중단할까요?',`<strong>${c.name}</strong>의 진행 <strong>${n(s.courseProgress[c.id].accumulatedSteps)}보</strong>가 사라집니다.<br>전체 걸음수, 수집한 엽서와 정산 전 누적된 걸음은 유지돼요.<br>다시 참여하면 0보부터 출발합니다.`,'여행 중단하기',true);if(!yes)return;action('abandon');completion=null;navigate('courses');toast('여행을 중단했어요. 새로운 여행을 골라 주세요.')}
async function selectCourse(id){const current=state().activeCourseId;if(id!==current&&state().courseProgress[current]?.startedAt){const yes=await confirm('현재 여행을 중단하고 바꿀까요?',`지금 코스에 쌓인 <strong>${n(state().courseProgress[current].accumulatedSteps)}보</strong>는 사라져요.<br>전체 걸음수, 수집한 엽서와 정산 전 걸음은 그대로 유지됩니다.`,'중단하고 새 여행 시작');if(!yes)return;}
 if(action('switch',{courseId:id})===false)return;completion=null;selected=Math.min(4,Math.floor(state().courseProgress[id].accumulatedSteps/10000));zoom=true;navigate('journey');}
function openDebug(){const s=state();openDialog('debug',modalHeader('테스트 걸음 입력','프로토타입에서 사용할 걸음을 직접 추가해 보세요.')+`<div class="modal-content"><p class="debug-description">실제 만보기와 연결하지 않은 리뷰용 화면입니다. 추가한 걸음은 지도에서 정산할 수 있어요.</p><div class="debug-metrics"><div><small>누적된 걸음</small><strong id="debug-pending">${n(s.unclaimedSteps)}보</strong></div><div><small>전체 걸음</small><strong>${n(s.lifetimeSteps)}보</strong></div></div><div class="step-buttons"><button data-add="1000">+1,000보</button><button data-add="5000">+5,000보</button><button data-add="10000">+10,000보</button></div><div class="reset-list"><button data-reset="reset-pending"><strong>누적 걸음수 리셋</strong><small>정산 전 걸음만 0으로</small></button><button data-reset="reset-course" ${!s.activeCourseId?'disabled':''}><strong>코스 진행 초기화</strong><small>${s.activeCourseId?active().shortName+' 진행과 이 코스의 엽서 5장만 초기화':'진행 중인 여행이 없어요'}</small></button><button data-reset="reset-lifetime"><strong>전체 걸음수 리셋</strong><small>전체 걸음만 0으로 · 진행과 엽서는 유지</small></button><button data-reset="reset-all"><strong>전체 데이터 초기화</strong><small>이 앱의 모든 여행 기록 삭제</small></button></div><button class="primary debug-close" data-dialog="close">${s.activeCourseId?'지도로 돌아가기':'여행 고르기'}</button></div>`,()=>{if(screen!=='journey')navigate('journey');else refreshJourneyKeepingScroll()})}
function refreshJourneyKeepingScroll(){if(screen!=='journey'){render();return}const v=$('.map-viewport'),left=v?.scrollLeft||0,top=v?.scrollTop||0;render();$('.map-viewport')?.scrollTo({left,top,behavior:'instant'})}
async function reset(type){if(type==='reset-pending'){action(type);refreshJourneyKeepingScroll();openDebug();toast('정산 전 걸음을 초기화했어요.');return}
 const prompts={'reset-course':['이 코스를 처음부터 시작할까요?',`${active().shortName} 진행 걸음과 수집한 엽서를 삭제합니다. 다른 코스의 엽서와 전체 걸음수는 유지돼요.`],'reset-lifetime':['전체 걸음수를 0으로 바꿀까요?','전체 걸음수만 초기화합니다. 현재 코스 진행과 수집한 엽서는 그대로 남아요.'],'reset-all':['모든 여행 기록을 지울까요?','이 앱에 저장된 걸음수와 모든 코스 진행, 수집한 엽서를 삭제합니다. 되돌릴 수 없어요.']};const yes=await confirm(...prompts[type],'초기화',true);if(yes){action(type);completion=null;selected=0;refreshJourneyKeepingScroll();toast('선택한 기록을 초기화했어요.')}openDebug();}
function postcardArt(c,w,extra=''){return c.map?`<div class="post-art ${extra}"><img src="${c.map}" alt="${w.name} 지도 일러스트" style="--art-x:${w.art[0]/10};--art-y:${w.art[1]/15}" loading="lazy"></div>`:`<div class="post-art ${extra}"></div>`}
function openJournal(tab=journalTab){journalTab=tab;const c=courseById[tab],count=c.waypoints.filter(w=>state().collectedPostcards[`${c.id}_${w.id}`]).length;openDialog('journal',modalHeader('나의 엽서 도감',`수집한 풍경 ${Object.keys(state().collectedPostcards).length} / 25`)+`<div class="journal-tabs" role="tablist" aria-label="코스별 엽서">${courses.map(x=>`<button role="tab" id="tab-${x.id}" aria-selected="${x.id===tab}" aria-controls="journal-panel" data-journal-tab="${x.id}">${x.shortName}</button>`).join('')}</div><div id="journal-panel" role="tabpanel" aria-labelledby="tab-${tab}"><div class="journal-summary"><span>${c.category}${!c.enabled?' · Coming soon':''}</span><span>${count}/5장</span></div><div class="journal-grid">${c.waypoints.map(w=>{const unlocked=state().collectedPostcards[`${c.id}_${w.id}`];return `<button class="journal-card ${unlocked?'':'locked'}" style="--post-color:${unlocked?w.color:'#cbd2c4'}" ${unlocked?`data-postcard="${c.id}_${w.id}"`:'disabled'} aria-label="${w.name}, ${unlocked?'수집한 엽서 보기':'아직 미획득'}"><div class="journal-art">${postcardArt(c,w,'journal-art')}${!unlocked?`<div class="locked-cover">${icon('lock')}<span>${c.enabled?'미발견':'준비 중'}</span></div>`:''}</div><div class="journal-card-copy"><h3>${w.name}</h3><small>${n(w.steps)}보${unlocked?' · 획득':''}</small></div></button>`}).join('')}</div></div><div class="storage-info">엽서는 코스를 바꾸거나 완주해도 남아 있어요.<br>기록은 이 기기의 브라우저에 저장됩니다.</div>`)}
function showPostcard(courseId,waypointId,{event=null,fromJournal=false}={}){
 const c=courseById[courseId],w=c.waypoints.find(x=>x.id===waypointId),record=state().collectedPostcards[`${courseId}_${waypointId}`];if(!record)return;
 const newly=event?.unlocked.includes(waypointId),queued=!!event&&!!arrival,finalCard=!queued||arrival.index===arrival.event.crossed.length-1,completed=event?.completed&&finalCard;const title=completed?'여정 완주!':event?(newly?'새로운 엽서 해금!':'다시 만난 풍경'):'여행의 한 장면';
 const date=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(record.unlockedAt));
 openDialog('postcard',modalHeader(title,c.name+(queued?` · 도착 엽서 ${arrival.index+1} / ${arrival.event.crossed.length}`:''))+(event?`<p class="arrival-copy">${w.name}에 도착했어요</p>`:'')+(completed?`<p class="completion-copy">50,000보 완주! 기록을 간직하고 다시 출발해요.</p>`:'')+`<button class="flip-card" data-dialog="flip" aria-label="엽서 뒷면 보기" aria-pressed="false" style="--post-color:${w.color}"><div class="flip-inner"><div class="flip-face front" aria-hidden="false">${postcardArt(c,w)}<div class="post-title"><small>${c.shortName.toUpperCase()} · ${String(w.id).padStart(2,'0')}</small><h3>${w.name}</h3><p>${w.subtitle}</p></div></div><div class="flip-face back" aria-hidden="true"><div class="post-back-header"><span class="kicker">DEAR TRAVELER</span><span class="stamp">${n(w.steps)}보</span></div><p class="post-story">${w.story}</p><div class="post-date">처음 만난 날<br>${date}<br>${completed&&event.overflow?`초과 ${n(event.overflow)}보는 전체 걸음에 포함`:`몬티와 함께한 ${c.shortName} 여행`}</div></div></div></button><p class="flip-hint">엽서를 눌러 뒷면의 이야기를 읽어 보세요.</p><div class="post-actions">${queued&&arrival.event.crossed.length>1?`<button class="secondary" data-dialog="arrival-prev" ${arrival.index===0?'disabled':''}>이전 엽서</button>`:''}<button class="primary" data-dialog="${queued&&!finalCard?'arrival-next':fromJournal?'journal-back':'close'}">${queued&&!finalCard?'다음 엽서':completed?'다시 출발하기':fromJournal?'도감으로 돌아가기':'여행 계속하기'}</button></div>`,()=>{arrival=null;if(completion){completion=null;selected=0;render();requestAnimationFrame(()=>centerMap(false))}});
}
function showArrival(index){if(!arrival)return;arrival.index=index;showPostcard(arrival.event.courseId,arrival.event.crossed[index],{event:arrival.event})}
function reducedMotion(){return window.matchMedia('(prefers-reduced-motion: reduce)').matches}
function claim(){if(moving||!state().unclaimedSteps)return;const previous=state(),oldLifetime=previous.lifetimeSteps;const event=action('claim');if(!event)return;moving=true;motionId++;const run=motionId;app.setAttribute('aria-busy','true');app.querySelectorAll('button,select').forEach(b=>b.disabled=true);$('.you-pin').classList.add('walking');const start=performance.now(),duration=reducedMotion()?1:Math.min(2400,1100+(event.to-event.from)/35);
 function tick(now){if(run!==motionId)return;const t=Math.min(1,(now-start)/duration),ease=t*t*(3-2*t),value=event.from+(event.to-event.from)*ease;updatePosition(value);$('#pending-steps').textContent=n(event.claimed*(1-ease));$('#lifetime-steps').textContent=n(oldLifetime+event.claimed*ease);if(zoom)centerMap(false,value);if(t<1){requestAnimationFrame(tick);return}moving=false;app.removeAttribute('aria-busy');if(event.completed)completion=event;selected=event.latest?Number(event.latest)-1:Math.min(4,Math.floor(event.to/10000));refreshJourneyKeepingScroll();if(event.crossed.length){arrival={event,index:0};showArrival(0);}else toast(`${n(event.claimed)}보를 여정에 더했어요.`)}requestAnimationFrame(tick);
}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||moving)return;if(b.dataset.course){selectCourse(b.dataset.course);return}if(b.dataset.waypoint!==undefined){selected=Number(b.dataset.waypoint);app.querySelectorAll('.waypoint').forEach(x=>x.classList.toggle('is-selected',x===b));renderDetail();return}switch(b.dataset.action){case 'home':case 'courses':case 'journey':navigate(b.dataset.action);break;case 'abandon':abandonCourse();break;case 'debug':openDebug();break;case 'journal':openJournal();break;case 'claim':claim();break;case 'zoom':zoom=!zoom;drawMap();$('[data-action=zoom] span').textContent=zoom?'전체 경로':'확대해서 보기';if(zoom)centerMap();else $('.map-viewport').scrollTo({left:0,top:0});break;case 'locate':centerMap();break;case 'selected-postcard':showPostcard(active().id,active().waypoints[selected].id);break}});
dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.add){action('add',{amount:Number(b.dataset.add)});const pending=$('#debug-pending',dialog);if(pending)pending.textContent=n(state().unclaimedSteps)+'보';toast(`+${n(Number(b.dataset.add))}보를 추가했어요.`);return}if(b.dataset.reset){reset(b.dataset.reset);return}if(b.dataset.journalTab){openJournal(b.dataset.journalTab);return}if(b.dataset.postcard){const [courseId,waypointId]=b.dataset.postcard.split('_');showPostcard(courseId,waypointId,{fromJournal:true});return}switch(b.dataset.dialog){case 'arrival-next':showArrival(arrival.index+1);break;case 'arrival-prev':showArrival(arrival.index-1);break;case 'close':closeDialog();break;case 'confirm':closeDialog('confirm');break;case 'journal-back':openJournal();break;case 'flip':{const flipped=b.classList.toggle('flipped');b.setAttribute('aria-label',flipped?'엽서 앞면 보기':'엽서 뒷면 보기');b.setAttribute('aria-pressed',flipped);$('.front',b).setAttribute('aria-hidden',flipped);$('.back',b).setAttribute('aria-hidden',!flipped);break}}});
window.addEventListener('hashchange',()=>{if(moving){history.replaceState(null,'','#journey');return}const target=location.hash.slice(1);navigate(target)});
window.addEventListener('storage',e=>{if(e.key!==STORAGE_KEY&&e.key!==null)return;motionId++;moving=false;completion=null;arrival=null;if(dialog.open)closeDialog();store.reload(e.newValue);render();toast('다른 창에서 변경한 기록을 반영했어요.')});
let lastWidth='';new ResizeObserver(()=>{if(screen!=='journey'||moving)return;const w=app.clientWidth+'x'+app.clientHeight;if(w===lastWidth)return;lastWidth=w;drawMap();centerMap(false)}).observe(app);
screen=['home','courses','journey'].includes(location.hash.slice(1))?location.hash.slice(1):'home';if(screen==='journey'&&!state().activeCourseId){screen='courses';history.replaceState(null,'','#courses');}if(screen==='journey')action('start');render();if(screen==='journey')requestAnimationFrame(()=>centerMap(false));
registerJourneyReader(state);
